import Chipss from '@/components/Chipss'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Navebar from '@/components/Navebar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Chipssss</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navebar />
      <Hero/>
      <Chipss/>
      <Footer/>
    </>
  )
}
